### ISSUE TITLE
Syntax discussion

### ISSUE THREAD

**Issue by Dandigit** [gwn-lang/GWN#1]
Yo! (insert Mal'is-tr reference here)

GWN has the potential to be pretty cool and experimental. Essentially, the core of the language would be passing data around with `->` and `<-`.

I think it should be a functional language, in a similar vein to Haskell, but not quite as poncy and pure. So no statements, just expressions, and no loops or anything like that (just recursion).

Functions would just be lambdas with names. Here's an idea for lambda syntax:
```
plus <- {x y |
    x + y
}

2 -> plus <- 2
=> 4
```
The lambda is created with curly braces, and `|` separates the arguments from the body.

As GWN would be functional, there'd be no variables, just constants. Every constant is just a function that takes no arguments, e.g:
```
x <- 21
# is equivalent to
x <- {| 21}
```

All functions should be curried (for partial application) so we can do things like this:
```
times <- {x y |
    x * y
}

3 -> times <- 4
=> 12

3 -> 4 -> times
=> 12

times <- 3 <- 4
=> 12

triple <- times <- 3
triple <- 3
=> 9
```
This would be similar to defining a function in an imperative language (say, JS) like this:
```
function multiply(x) {
    return function (y) {
        return x * y
    }
}

multiply(3)(4)
=> 12

const triple = multiply(3)
triple(20)
=> 60
```

And thanks to the nice data passing syntax, we can do things like this:
```
"Hello World!" -> splitBy <- " "
=> ["Hello", "World"]
```
This would be familiar to both object-oriented and functional programmers. In object-oriented code:
```
"Hello World".splitBy(" ")
```
Or in functional code:
```
"Hello World" |> splitBy " "
```

Let me know what you think so far.

Notify @SimpleBinary

**Comment by Dandigit** [comment]
@SimpleBinary Also, maybe we could make Mal'is-tr the mascot :)

**Comment by SimpleBinary** [comment]
@Dandigit Great ideas, I agree, it has the potential to be a good language.

**Comment by Dandigit** [comment]
@SimpleBinary Yeah, I think we took for granted just how great an idea `<-` and `->` were.

**Comment by Dandigit** [comment]
@SimpleBinary Also, can you please give me write access to this repository? I can't edit anything.

**Comment by SimpleBinary** [comment]
@Dandigit I invited you to the origination, you should have write access.

**Comment by Dandigit** [comment]
@SimpleBinary I joined, but I'm a Member, not an Owner, so I can't edit things.

**Comment by SimpleBinary** [comment]
@Dandigit I just upgraded you

**Comment by Dandigit** [comment]
@SimpleBinary Thanks, I'll test.

**Comment by Dandigit** [comment]
@SimpleBinary Yep, working :)

**Comment by Dandigit** [comment]
@SimpleBinary I'm going to move this to the team now.

**Comment by SimpleBinary** [comment]
@Dandigit I close the issues
