### ISSUE TITLE
Implementation discussion

### ISSUE THREAD

**Issue by Dandigit** [gwn-lang/GWN#2]
So, the other side of the language discussion is how we'll implement it.

Firstly, we need to choose a language:
- We both know a fair bit of Python, so that's a good candidate for the interpreter.
- Both of us don't know much Rust, but we __have__ expressed interest in learning it, so this could be a good project. Plus, Rust is faster and will scale better, I imagine.

Once we've chosen a language, we'll move on to other things:
- Tree or bytecode? I'm thinking bytecode.
- Possibility of a compiler sometime in the future? Rust->LLVM bindings?

What do you think?

Notify @SimpleBinary

**Comment by SimpleBinary** [comment]
@Dandigit I think Python is a good idea for an Interpreter, but I do everything in python, so I think it would also be nic to write something in Rust for a change. PS: I have made a team at @gwn-lang/gwn

**Comment by Dandigit** [comment]
@SimpleBinary Thanks, I think I'll move these discussions over there.

**Comment by BonfireScratch** [comment]
@Dandigit how does bytecode work?
